[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "timewise-guardian-client"
version = "0.1.0"
description = "Client application for Timewise Guardian - A Home Assistant based parental control system"
readme = "README.md"
authors = [
    { name = "Kim Asplund", email = "kim.asplund@gmail.com" }
]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: System :: Monitoring",
]
keywords = ["home-assistant", "parental-control", "monitoring"]
dependencies = [
    "aiohttp>=3.9.1",
    "psutil>=5.9.6",
    "pyyaml>=6.0.1",
    "websockets>=12.0",
    "pywin32>=306; platform_system == 'Windows'",
    "dbus-python>=1.3.2; platform_system == 'Linux'",
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://asplund.kim"
Repository = "https://github.com/kimasplund/timewise-guardian"
Documentation = "https://github.com/kimasplund/timewise-guardian/wiki"

[project.scripts]
twg-client = "timewise_guardian_client.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/timewise_guardian_client"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
    "LICENSE",
    "README.md",
]

[tool.hatch.version]
path = "src/timewise_guardian_client/__init__.py" 