---
# Home Assistant connection settings
homeassistant:
  url: "http://192.168.2.20:8123"
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2YjE4MjYxYWQxYTA0YWM3OTgwYmM2ZGEyZTE3MjZkZSIsImlhdCI6MTczNTQxODA2OSwiZXhwIjoyMDUwNzc4MDY5fQ.Qg1LD20T6dSTh0b1kl7Uz74uFyGuU_unC3IBErL-mKQ"

# Client settings
client:
  auto_register: true
  sync_interval: 60  # Seconds between syncs with HA
  memory_management:
    max_client_memory_mb: 100
    cleanup_interval_minutes: 5
    memory_threshold: 90

# All other settings (categories, time limits, restrictions, etc.) are managed through Home Assistant 